//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedTexts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category must be selected..
        /// </summary>
        internal static string CategoryMustBeSelected {
            get {
                return ResourceManager.GetString("CategoryMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (from resource).
        /// </summary>
        internal static string ConventionalDataAnnotationsModel_FirstName {
            get {
                return ResourceManager.GetString("ConventionalDataAnnotationsModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is required (from resource).
        /// </summary>
        internal static string ConventionalDataAnnotationsModel_FirstName_Required {
            get {
                return ResourceManager.GetString("ConventionalDataAnnotationsModel_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (from resource).
        /// </summary>
        internal static string ConventionalDataAnnotationsModel_Weight {
            get {
                return ResourceManager.GetString("ConventionalDataAnnotationsModel_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight required (from resource).
        /// </summary>
        internal static string ConventionalDataAnnotationsModel_Weight_Required {
            get {
                return ResourceManager.GetString("ConventionalDataAnnotationsModel_Weight_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (from resource).
        /// </summary>
        internal static string ConventionalFluentModel_FirstName {
            get {
                return ResourceManager.GetString("ConventionalFluentModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is required (from resource).
        /// </summary>
        internal static string ConventionalFluentModel_FirstName_Required {
            get {
                return ResourceManager.GetString("ConventionalFluentModel_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (from resource).
        /// </summary>
        internal static string ConventionalFluentModel_Weight {
            get {
                return ResourceManager.GetString("ConventionalFluentModel_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight required (from resource).
        /// </summary>
        internal static string ConventionalFluentModel_Weight_Required {
            get {
                return ResourceManager.GetString("ConventionalFluentModel_Weight_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string CreateValidationSummary {
            get {
                return ResourceManager.GetString("CreateValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization by Conventions for Data Annotations.
        /// </summary>
        internal static string DataAnnotationsConventionTitle {
            get {
                return ResourceManager.GetString("DataAnnotationsConventionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        internal static string EditValidationSummary {
            get {
                return ResourceManager.GetString("EditValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization by Conventions for Fluent Metadata Configuration.
        /// </summary>
        internal static string FluentMetadataConventionTitle {
            get {
                return ResourceManager.GetString("FluentMetadataConventionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Call.
        /// </summary>
        internal static string Home_MethodCall {
            get {
                return ResourceManager.GetString("Home_MethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Property.
        /// </summary>
        internal static string Home_ModelProperty {
            get {
                return ResourceManager.GetString("Home_ModelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Home_Result {
            get {
                return ResourceManager.GetString("Home_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string Home_Scenario {
            get {
                return ResourceManager.GetString("Home_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Demo.
        /// </summary>
        internal static string Home_ValidationDemo {
            get {
                return ResourceManager.GetString("Home_ValidationDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (from Resource).
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataAnnotations conventions.
        /// </summary>
        internal static string Menu_DataAnnotations {
            get {
                return ResourceManager.GetString("Menu_DataAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentConfiguration conventions.
        /// </summary>
        internal static string Menu_FluentConfigurations {
            get {
                return ResourceManager.GetString("Menu_FluentConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations Example.
        /// </summary>
        internal static string Menu_Products {
            get {
                return ResourceManager.GetString("Menu_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name (from Resource).
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank..
        /// </summary>
        internal static string NameCannotBeBlank {
            get {
                return ResourceManager.GetString("NameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be more than 64 characters..
        /// </summary>
        internal static string NameCannotBeMoreThanSixtyFourCharacters {
            get {
                return ResourceManager.GetString("NameCannotBeMoreThanSixtyFourCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price cannot be blank..
        /// </summary>
        internal static string PriceCannotBeBlank {
            get {
                return ResourceManager.GetString("PriceCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be between 10.00-1000.00..
        /// </summary>
        internal static string PriceMustBeBetweenTenToThousand {
            get {
                return ResourceManager.GetString("PriceMustBeBetweenTenToThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select category].
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier must be selected..
        /// </summary>
        internal static string SupplierMustBeSelected {
            get {
                return ResourceManager.GetString("SupplierMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Required Fallback Error Message (from resource).
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
