//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Kazi Manzur Rashid")]
[assembly: AssemblyCopyright("Copyright © Kazi Manzur Rashid 2009-2011")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("2.5.0.9999")]
[assembly: AssemblyFileVersion("2.5.0.9999")]


