// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mvc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Configurator", Scope = "type", Target = "MvcExtensions.AbstractRemoteValidationConfigurator`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Configurator", Scope = "type", Target = "MvcExtensions.RemoteValidationConfigurator`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "MvcExtensions.AbstractRemoteValidationConfigurator`1.#MvcExtensions.IRemoteValidationConfigurator`1<!0>.ModelMetadataItemBuilder")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "MvcExtensions.IModelMetadataAdditionalSetting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Configurator", Scope = "type", Target = "MvcExtensions.IRemoteValidationConfigurator`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "MvcExtensions.StringMetadataItemBuilder.#UrlExpression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "MvcExtensions.StringMetadataItemBuilder.#UrlErrorMessage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "MvcExtensions.StringMetadataItemBuilder.#UrlErrorMessageResourceName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "MvcExtensions.FlashHtmlExtensions.#Flash(System.Web.Mvc.HtmlHelper,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int32>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Decimal>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Double>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int16>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Single>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int16>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.DateTime>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Decimal>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Byte>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int64>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure`1(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int64>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int32>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Byte>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Boolean>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Double>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Single>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ModelMetadataConfiguration`1.#Append`1(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "MvcExtensions.IModelMetadataAdditionalSetting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RangeMetadataItemBuilderExtensions.#Range`1(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<!!0>>,!!0,!!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RangeMetadataItemBuilderExtensions.#Range`1(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<!!0>>,!!0,!!0,System.Type,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RangeMetadataItemBuilderExtensions.#Range`1(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<!!0>>,!!0,!!0,System.Func`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RangeMetadataItemBuilderExtensions.#Range`1(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<!!0>>,!!0,!!0,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ValueTypeMetadataItemBuilderExtensions.#FormatAsCurrency(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<System.Decimal>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ValueTypeMetadataItemBuilderExtensions.#FormatAsDateOnly(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.ValueTypeMetadataItemBuilderExtensions.#FormatAsTimeOnly(MvcExtensions.ModelMetadataItemBuilder`1<System.Nullable`1<System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "MvcExtensions.ModelMetadataItemBuilder`1.#ValidateBy`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "MvcExtensions.ModelMetadataItemBuilder`1.#Validate(System.Func`2<!0,System.Boolean>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "MvcExtensions.ModelMetadataItemBuilder`1.#Validate`1(System.Func`2<!!0,System.Boolean>,System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationExtensions.#Remote`1(MvcExtensions.ModelMetadataItemBuilder`1<!!0>,System.Func`2<MvcExtensions.RemoteValidationConfigurator`1<!!0>,MvcExtensions.AbstractRemoteValidationConfigurator`1<!!0>>,System.String,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationExtensions.#Remote`1(MvcExtensions.ModelMetadataItemBuilder`1<!!0>,System.Func`2<MvcExtensions.RemoteValidationConfigurator`1<!!0>,MvcExtensions.AbstractRemoteValidationConfigurator`1<!!0>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationExtensions.#Remote`1(MvcExtensions.ModelMetadataItemBuilder`1<!!0>,System.Func`2<MvcExtensions.RemoteValidationConfigurator`1<!!0>,MvcExtensions.AbstractRemoteValidationConfigurator`1<!!0>>,System.Func`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationExtensions.#Remote`1(MvcExtensions.ModelMetadataItemBuilder`1<!!0>,System.Func`2<MvcExtensions.RemoteValidationConfigurator`1<!!0>,MvcExtensions.AbstractRemoteValidationConfigurator`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Web.Mvc.ActionResult>>,System.String,System.Collections.Generic.IEnumerable`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Web.Mvc.ActionResult>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Web.Mvc.ActionResult>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Web.Mvc.ActionResult>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Web.Mvc.ActionResult>>,System.Collections.Generic.IEnumerable`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Func`2<!0,System.Web.Mvc.ActionResult>>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvcExtensions.RemoteValidationConfigurator`1.#For`1(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Func`2<!0,System.Web.Mvc.ActionResult>>>)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MvcExtensions.ExpressionVisitorHelper.#GetFullPropertyName(System.Linq.Expressions.Expression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "MvcExtensions.ExpressionVisitorHelper.#GetPropertyName(System.Linq.Expressions.Expression)")]
