//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExtensions.FluentMetadata.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcExtensions.FluentMetadata.Tests.Resources.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyWithDisplayAttributeMatchingResourceKey_FromResource.
        /// </summary>
        public static string AttrDummyDisplayModel_PropertyWithDisplayAttributeMatchingResourceKey {
            get {
                return ResourceManager.GetString("AttrDummyDisplayModel_PropertyWithDisplayAttributeMatchingResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName From Resource.
        /// </summary>
        public static string AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName {
            get {
                return ResourceManager.GetString("AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt FromResource.
        /// </summary>
        public static string AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt {
            get {
                return ResourceManager.GetString("AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrLocalizationModel_AttrLocalizedByKey_From_Resource.
        /// </summary>
        public static string AttrLocalizationModel_AttrLocalizedByKey {
            get {
                return ResourceManager.GetString("AttrLocalizationModel_AttrLocalizedByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizationModel_AttrLocalizedByKey_Required_From_Resource.
        /// </summary>
        public static string AttrLocalizationModel_AttrLocalizedByKey_Required {
            get {
                return ResourceManager.GetString("AttrLocalizationModel_AttrLocalizedByKey_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be used!.
        /// </summary>
        public static string AttrLocalizationModel_AttrLocalizedByKeyWithCustomMessageForPropertyFromRes_Required {
            get {
                return ResourceManager.GetString("AttrLocalizationModel_AttrLocalizedByKeyWithCustomMessageForPropertyFromRes_Requi" +
                        "red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomMessageForProperty_FromResource.
        /// </summary>
        public static string CustomMessageForProperty {
            get {
                return ResourceManager.GetString("CustomMessageForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyWithDisplayAttributeMatchingResourceKey_FromResource.
        /// </summary>
        public static string DummyDisplayModel_PropertyWithDisplayAttributeMatchingResourceKey {
            get {
                return ResourceManager.GetString("DummyDisplayModel_PropertyWithDisplayAttributeMatchingResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttrDummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName From Resource.
        /// </summary>
        public static string DummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName {
            get {
                return ResourceManager.GetString("DummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt  FromResource.
        /// </summary>
        public static string DummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt {
            get {
                return ResourceManager.GetString("DummyDisplayModel_PropertyWithMatchingResourceKeyByClassAndName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizationModel_LocalizedByKey_From_Resource.
        /// </summary>
        public static string LocalizationModel_LocalizedByKey {
            get {
                return ResourceManager.GetString("LocalizationModel_LocalizedByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizationModel_LocalizedByKey_Required_From_Resource.
        /// </summary>
        public static string LocalizationModel_LocalizedByKey_Required {
            get {
                return ResourceManager.GetString("LocalizationModel_LocalizedByKey_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value should not be used!.
        /// </summary>
        public static string LocalizationModel_LocalizedByKeyWithCustomMessageForPropertyFromRes_Required {
            get {
                return ResourceManager.GetString("LocalizationModel_LocalizedByKeyWithCustomMessageForPropertyFromRes_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyToTestResNamePartialMetadata_FromResource1.
        /// </summary>
        public static string PropertyToTestResNamePartialMetadata {
            get {
                return ResourceManager.GetString("PropertyToTestResNamePartialMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyWithMatchingResourceKey FromResource.
        /// </summary>
        public static string PropertyWithMatchingResourceKey {
            get {
                return ResourceManager.GetString("PropertyWithMatchingResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyWithMatchingResourceKey_Prompt FromResource.
        /// </summary>
        public static string PropertyWithMatchingResourceKey_Prompt {
            get {
                return ResourceManager.GetString("PropertyWithMatchingResourceKey_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation_Required_FromResource.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
